# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5ULKVkSPyUV3kJBqt8PqP3tSnk-0FpD
"""

from fastapi import FastAPI
from transformers import pipeline
from pydantic import BaseModel
from fastapi.responses import RedirectResponse

# 1. Initialize our tools
app = FastAPI()
sentiment_model = pipeline("sentiment-analysis")

# 2. The Two-Pointer Algorithm (The "Big Tech" way)
def is_palindrome(text: str) -> bool:
    clean_text = "".join(filter(str.isalnum, text)).lower()
    left, right = 0, len(clean_text) - 1

    while left < right:
        if clean_text[left] != clean_text[right]:
            return False
        left += 1
        right -= 1
    return True

# 3. Define the Request Data Shape
class AnalysisRequest(BaseModel):
    word: str


@app.get("/")
async def home():
    return {
        "status": "Online",
        "message": "Welcome to the Hybrid AI Analyzer!",
        "instructions": "Go to /docs to test the Palindrome and Sentiment analysis."
    }






# 4. The API Endpoint
@app.post("/analyze")
async def analyze_word(request: AnalysisRequest):
    user_word = request.word

    # Run the Algorithm
    palindrome_status = is_palindrome(user_word)

    # Run the Transformer
    ai_result = sentiment_model(user_word)[0]

    return {
        "word": user_word,
        "is_palindrome": palindrome_status,
        "sentiment": ai_result["label"],
        "confidence_score": round(ai_result["score"], 4),
        "message": "Logic and AI have successfully met!"
    }

